# version: '3.8'

# services:
#   auth:
#     build:
#       context: ./services/auth
#     ports:
#       - "8080:8080"
#     environment:
#       - DB_URL=jdbc:postgresql://db:5432/auth_db
#     depends_on:
#       - db

#   order:
#     build:
#       context: ./services/order
#     ports:
#       - "8081:8081"
#     environment:
#       - DB_URL=jdbc:postgresql://db:5432/order_db
#     depends_on:
#       - db

#   payment:
#     build:
#       context: ./services/payment
#     ports:
#       - "8082:8082"
#     environment:
#       - DB_URL=jdbc:postgresql://db:5432/payment_db
#     depends_on:
#       - db

#   user:
#     build:
#       context: ./services/user
#     ports:
#       - "8083:8083"
#     environment:
#       - DB_URL=jdbc:postgresql://db:5432/user_db
#     depends_on:
#       - db

#   db:
#     image: postgres:13
#     env_file:
#       - ./influxDB/.env    
#     ports:
#       - "5432:5432"
