spring:
  application:
    name: config-server
  main:
    allow-bean-definition-overriding: true
  cloud:
    bus:
      enable: true
    stream:
      kafka:
        binder:
          brokers: $kafka-server-name-in-docker:9092
      bindings:
        input:
          destination: springCloudBus
    config:
      server:
        native:
          search-locations: file:./config-repo 
server:
  port: 8888
eureka:
  client:
    service-url:
      # CHANGE
      defaultZone: $eureka-service-name-in-docker:8761/eureka/ 
    enabled: true
    register-with-eureka: true
    fetch-registry: false     
  instance:
      hostname: config-server
      instance-id: ${spring.application.name}
management:
  endpoints:
    web:
      exposure:
        include:  "*"