spring:
  application:
    name: config-server
  main:
    allow-bean-definition-overriding: true
  cloud:
    bus:
      enable: true
    discovery:
      enabled: true    # 如果使用 Eureka 服务发现
      service-id: ${spring.application.name}
    stream:
      kafka:
        binder:
          brokers: $localhost-or-kafka-docker-server-name:9092
      bindings:
        input:
          destination: springCloudBus
    config:
      server:
        native:
          search-locations: file:./config-repo 
server:
  port: 8888
eureka:
  client:
    service-url:
      # CHANGE
      defaultZone: http://$localhost-or-eureka-docker-server-name:8761/eureka/ 
    enabled: true
    register-with-eureka: true
    fetch-registry: false     
  instance:
      hostname: ${spring.application.name}
      instance-id: ${spring.application.name}
management:
  endpoints:
    web:
      exposure:
        include:  "*"
logging:
  level:
    root: WARN
    com.codera: INFO