spring:
  application:
    name: auth-resource-server
  main:
    allow-bean-definition-overriding: true
  config:
    import: "optional:configserver:"
  # security:
  #   oauth2:
  #     resourceserver:
  #       jwt:
  #         issuer-uri: http://auth-server:8080/oauth2/default # 替换为你的 OAuth2 签发者地址
  #         jwk-set-uri: http://auth-server:8080/oauth2/jwks  # 替换为你的 JWK 地址
  cloud:
    discovery:
      enabled: true    # 如果使用 Eureka 服务发现
      service-id: ${spring.application.name} # 注册于Eureka中的服务名
    config:
      name: auth-resource-server # 用于在config-server的repo中匹配文件名规则
      profile: dev     # 环境
server:
  port: 8084
eureka:
  client:
    service-url:
      # CHANGE
      defaultZone: http://eureka:8761/eureka/ 
    register-with-eureka: true
    fetch-registry: true     
  instance:
      hostname: ${spring.application.name}
      instance-id: ${spring.application.name}
