apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090  
    isDefault: true  
    editable: true
    
  # - name: InfluxDB  # // prod
  #   type: influxdb
  #   access: proxy
  #   url: http://influx:8086
  #   database: hospitalbucket
  #   user: hospital
  #   secureJsonData:
  #     token: HOSPITALTOKEN
  #   isDefault: false  
  #   editable: true
  #   version: 1
  #   jsonData:
  #     httpMode: POST
  #     organization: surginus
  #     defaultBucket: hospitalbucket
  #     version: Flux 

