spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin 
      password: admin
server:
  port: 8761  
eureka:
  client:
    enabled: false
    register-with-eureka: false  
    fetch-registry: false      
  server:
    enable-self-preservation: false 
management:
  endpoints:
    web:
      exposure:
        include: "*"