spring:
  application:
    name: eureka-server
server:
  port: ${port:8761}
eureka:
  instance:
    hostname: $localhost-or-eureka-docker-server-name  
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    registerWithEureka: false
    fetchRegistry: false      
    serviceUrl:
      defaultZone: http://$localhost-or-eureka-docker-server-name:8761/eureka
  server:
    enable-self-preservation: false 
    waitTimeInMsWhenSyncEmpty: 0
management:
  endpoints:
    web:
      exposure:
        include: "*"